### PR TITLE
Rollback comments/photos to known working state

### PR DESCRIPTION
**Pull request by pawptart**
Rolls back all controllers, models, and views. Attempted to clean the DB of all references to those tables. 

Removed references to comments / photos in the places model. Also removed the geocoder gem (it can be added back if you would like to do lat/long location in the future).

Removing this extra code resolved issues with not being able to create new places. Other functionality (like editing places) was untested. This is a base to continue working on the project.

### CODE REVIEW

**Comment by CarlH2019** [comment]
Thanks Tyler, that really helps. What is the best way for me to merge this into a new branch? i don't see what branch you did this on.

**Comment by pawptart** [comment]
Since I am not a part of your organization on GitHub, I forked your repository and created my own local branch. These changes are located in my own repository, so you won't see them in the organization's branches here. 

I am a little confused as to what you mean by merging into a new branch. This is a pull request that I've requested to merge into master. It wouldn't be a merge into a new branch.

**Comment by CarlH2019** [comment]
So I can go ahead and merge this into the master?

**Comment by pawptart** [comment]
It should be ready to go from my perspective.

However, I think it would be wise to have a teammate or two review this. I made a LOT of deletions and you are all more familiar with your codebase than I am.

**Comment by CarlH2019** [comment]
Sounds good man.

**Comment by CarlH2019** [comment]
would you like to be part of our organization?

**Pull request merged**
